CREATE TABLE IF NOT EXISTS GetMessageTrackingLog (
    EventHash CHAR(64) NULL,
    `Timestamp` DATETIME(6) NULL,
    ClientIp VARCHAR(500) NULL,
    ClientHostname VARCHAR(500) NULL,
    ConnectorId VARCHAR(500) NULL,
    `Source` VARCHAR(500) NULL,
    EventId VARCHAR(500) NULL,
    InternalMessageId VARCHAR(500) NULL,
    MessageId VARCHAR(1000) NULL,
    NetworkMessageId VARCHAR(500) NULL,
    Recipients TEXT NULL,
    RecipientStatus TEXT NULL,
    TotalBytes BIGINT NULL,
    RecipientCount INT NULL,
    MessageSubject TEXT NULL,
    Sender VARCHAR(500) NULL,
    ReturnPath VARCHAR(500) NULL,
    Directionality VARCHAR(500) NULL,
    OriginalClientIp VARCHAR(500) NULL,
    TransportTrafficType VARCHAR(500) NULL,
    UNIQUE KEY uq_tracking_event_hash (EventHash),
    KEY ix_tracking_timestamp (`Timestamp`),
    KEY ix_tracking_direction_event (`Timestamp`, Directionality, EventId),
    KEY ix_tracking_sender (`Timestamp`, Sender(191))
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
